import os
import json
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
import pickle

SCOPES = [
    "https://www.googleapis.com/auth/forms.body",
    "https://www.googleapis.com/auth/drive"
]

TOKEN_FILE = os.path.join(os.path.dirname(__file__), 'google_token.pickle')

# Store OAuth state and code_verifier temporarily for the callback
_oauth_state = {}

def get_auth_url(client_id, client_secret):
    client_config = {
        "web": {
            "client_id": client_id,
            "project_id": "intern-manager",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": client_secret,
            "redirect_uris": ["http://localhost:5055/oauth/callback"]
        }
    }
    
    flow = Flow.from_client_config(
        client_config,
        scopes=SCOPES,
        redirect_uri="http://localhost:5055/oauth/callback"
    )
    
    auth_url, state = flow.authorization_url(prompt='consent', access_type='offline')
    
    # Save the code verifier generated by oauthlib for PKCE validation
    if hasattr(flow, 'code_verifier'):
        _oauth_state['code_verifier'] = flow.code_verifier
        
    return auth_url

def save_token_from_code(code, client_id, client_secret):
    client_config = {
        "web": {
            "client_id": client_id,
            "project_id": "intern-manager",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": client_secret,
            "redirect_uris": ["http://localhost:5055/oauth/callback"]
        }
    }
    
    flow = Flow.from_client_config(
        client_config,
        scopes=SCOPES,
        redirect_uri="http://localhost:5055/oauth/callback"
    )
    
    # Restore the code verifier for PKCE validation
    if 'code_verifier' in _oauth_state:
        flow.code_verifier = _oauth_state['code_verifier']
    
    flow.fetch_token(code=code)
    creds = flow.credentials
    
    with open(TOKEN_FILE, 'wb') as token:
        pickle.dump(creds, token)

def get_credentials():
    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, 'rb') as token:
            creds = pickle.load(token)
    return creds

def generate_google_form(title, fields_data, owner_email):
    """
    Creates a new Google Form using the Forms API and user OAuth token.
    Shares the Form with the given owner_email.
    Returns the Form link and ID.
    """
    try:
        creds = get_credentials()
        if not creds or not creds.valid:
            return {"success": False, "needs_auth": True, "msg": "يرجى تسجيل الدخول إلى جوجل أولاً"}

        forms_service = build('forms', 'v1', credentials=creds)
        drive_service = build('drive', 'v3', credentials=creds)

        # 1. Create the Form
        form = {
            "info": {
                "title": title,
                "documentTitle": title,
            }
        }
        result = forms_service.forms().create(body=form).execute()
        form_id = result["formId"]
        responder_uri = result["responderUri"]

        # 2. Add Questions
        requests_list = []
        index = 0
        
        for field in fields_data:
            question_item = {
                "createItem": {
                    "item": {
                        "title": field.get("label", "سؤال بدون عنوان"),
                        "questionItem": {
                            "question": {
                                "required": field.get("required", False),
                            }
                        }
                    },
                    "location": {
                        "index": index
                    }
                }
            }

            field_type = field.get("type", "text")
            # Map internal types to Google Forms types
            if field_type in ["text", "number", "email", "tel"]:
                question_item["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": False
                }
            elif field_type == "textarea":
                question_item["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": True
                }
            elif field_type == "date":
                question_item["createItem"]["item"]["questionItem"]["question"]["dateQuestion"] = {
                    "includeYear": True,
                    "includeTime": False
                }
            else:
                # Default to short text
                question_item["createItem"]["item"]["questionItem"]["question"]["textQuestion"] = {
                    "paragraph": False
                }

            requests_list.append(question_item)
            index += 1

        if requests_list:
            forms_service.forms().batchUpdate(
                formId=form_id,
                body={"requests": requests_list}
            ).execute()

        # 3. Share with the owner_email
        if owner_email:
            try:
                drive_service.permissions().create(
                    fileId=form_id,
                    body={
                        "type": "user",
                        "role": "writer", # Writer permission lets them edit and view responses
                        "emailAddress": owner_email
                    },
                    fields="id"
                ).execute()
            except Exception as share_err:
                # Ignore share errors to not block the success return
                print(f"Failed to share with {owner_email}: {share_err}")

        return {
            "success": True,
            "formId": form_id,
            "responderUri": responder_uri
        }

    except Exception as e:
        return {"success": False, "msg": f"حدث خطأ أثناء إنشاء النموذج: {str(e)}"}
